# -*- coding: utf-8 -*-
"""Text to speech in any language.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TiL5Ot9sKIyI5HRlM9VbzsWpWLpzVXnw
"""
from transformers import pipeline
from datasets import load_dataset
import torch
import soundfile as sf

from gtts import gTTS

def generate_audio(text, output_file):
    # Create a gTTS object with the English text
    tts = gTTS(text=text, lang='hi')
    # Save the generated audio to the specified output file path
    tts.save(output_file)

# Example usage:
# english_text = "This is an example English text."
# output_file = "output_audio.mp3"
# generate_audio(english_text, output_file)
# print('text to audio conversion has been done successfully')

# from gtts import gTTS

# # Your Hindi text
# hindi_text = """यहां आप अपने पढ़ने के कौशल का अभ्यास करने के लिए गतिविधियां पा सकते हैं। पढ़ने से आपको भाषा की समझ बेहतर बनाने और अपनी शब्दावली बनाने में मदद मिलेगी।

# इस खंड में स्व-अध्ययन पाठ कॉमन यूरोपियन फ्रेमवर्क ऑफ रेफरेंस फॉर लैंग्वेजेज (सीईएफआर) के आधार पर अंग्रेजी स्तर पर लिखे और व्यवस्थित किए गए हैं। विभिन्न प्रकार के पाठ और इंटरैक्टिव अभ्यास हैं जो आपको अपनी पढ़ाई में अच्छा प्रदर्शन करने, काम में आगे बढ़ने और अपने खाली समय में अंग्रेजी में संवाद करने के लिए आवश्यक पढ़ने के कौशल का अभ्यास कराते हैं।

# कौन सा स्तर चुनना है यह जानने के लिए हमारी निःशुल्क ऑनलाइन अंग्रेजी परीक्षा दें। A1 अंग्रेजी स्तर (प्राथमिक) से C1 अंग्रेजी स्तर (उन्नत) तक अपना स्तर चुनें, और जब भी यह आपके लिए सुविधाजनक हो, अपनी गति से अपने पढ़ने के कौशल में सुधार करें।"""
# # marathi_text="तू काय करतोस, तुझ्या कॉलेजचे नाव काय आहे ज्यामध्ये तू शिकत आहेस"
# # Create a gTTS object with the Hindi text
# tts = gTTS(text=hindi_text, lang='hi')
# # Create a gTTS object with the Hindi text
# # tts = gTTS(text=marathi_text, lang='mr')
# # Save the generated audio to a file (e.g., output.mp3)
# output_file = "output_Hindi_long.mp3"
# tts.save(output_file)

# # Optionally, play the generated audio
# import os
# os.system(f"mpg123 {output_file}")  # You may need to install mpg123

